version: '3'
services:
  metaapi-angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - .:/app
    working_dir: /app
    command: npm start
